[package]
name = "manix"
version = "0.8.0-dev"
edition = "2021"
license = "Apache-2.0"
description = "Nix documentation searcher"
authors = ["mlvzk <mlvzk@protonmail.com>", "n16hth4wk <lecoqjacob@gmail.com>"]

[dependencies]
anyhow = "1"
bincode = "1"
clap_complete = "4.4.9"
clap_complete_nushell = "4.4.2"
clap_mangen = "0.2.18"
colored = "2"
crc32fast = "1"
lazy_static = "1"
rayon = "1"
jq-rs = { version = "0.4.1", features = ["bundled"]}
rnix = "0.11"
rowan = "0.15"
roxmltree = "0.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "1"
walkdir = "2"
xdg = "2.5"

[dependencies.clap]
version = "4.4.18"
features = [ "derive" ]

[profile.release]
lto = true
codegen-units = 1
strip = true
debug = false
